### ISSUE TITLE
Consider adding AppStream metainfo

### ISSUE THREAD

**Issue by probonopd** [oskardolch/SteamCAD#6]
Please consider adding AppStream metainfo to `/usr/share/metainfo/steamcad.appdata.xml`.
This will make the entry at https://appimage.github.io/SteamCAD/ look much better.

Here is a tool that makes generating the file really easy:
http://output.jsbin.com/qoqukof

Thank you.

**Comment by probonopd** [comment]
![](https://user-images.githubusercontent.com/2480569/51800646-28ccec00-222a-11e9-9fd4-aa840fb2aae0.png)

**Comment by oskardolch** [comment]
I will check this occasionally. I am quite exhausted by the GNU build system at the moment :-)

**Comment by probonopd** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<component type="desktop-application">
	<id>steamcad</id>
	<metadata_license>CC0-1.0</metadata_license>
	<project_license>GPL-3.0</project_license>
	<name>SteamCAD</name>
	<summary> 2D CAD especially designed to draw steam locomotives</summary>
	<description>
		<p>SteamCAD is a drawing tool especially designed to create drawings of steam locomotives. The software is very lightweight, the user interface is minimalistic. As a result, the drawing area is not obscured by controls and can occupy the whole screen. This is what makes SteamCAD different from any other CAD. StreamCAD is focused on productivity, not on the fancy look.</p>
	</description>
	<launchable type="desktop-id">steamcad.desktop</launchable>
	<url type="homepage">https://github.com/oskardolch/SteamCAD</url>
	<screenshots>
		<screenshot type="default">
			<image>https://user-images.githubusercontent.com/2480569/51800646-28ccec00-222a-11e9-9fd4-aa840fb2aae0.png</image>
		</screenshot>
	</screenshots>
	<provides>
		<id>steamcad.desktop</id>
	</provides>
</component>
```

**Comment by probonopd** [comment]
This needs to be copied to `usr/share/metainfo/steamcad.appdata.xml`. That's it ;-)

**Comment by probonopd** [comment]
Among other things, you will bet a much more beautiful https://appimage.github.io/SteamCAD/ :+1:

**Comment by oskardolch** [comment]
OK, so I added the file, although not sure if it is correct. If yes, I could perhaps remove the files Linux/steamcad, Linux/steamcad.desktop and Images/steamcad_old.png as they don't seem to be in use anymore.

**Comment by probonopd** [comment]
Are you sure the file is in `usr/share/metainfo/steamcad.appdata.xml` inside the AppImage now? (You can check with `--appimage-extract`). I think it is still missing?

**Comment by oskardolch** [comment]
I thought that I did something wrong. I don't have an AppImage, that's the problem. The only I've done was adding the xml file into the project, and when running "make install", the xml file is copied to the /usr/share/metainfo folder on the target system.

**Comment by probonopd** [comment]
> I don't have an AppImage, that's the problem.

Err, actually you do: https://github.com/oskardolch/SteamCAD/releases

**Comment by oskardolch** [comment]
Yea, I think in this case I need your new .travis.yml script, so that the package gets built by the GNU automated build. So far there is still the old .travis.yml in my master branch, with the build using the manual makefile.gcc and your hack to get the image somehow. Shall I pull it from your fork?

**Comment by probonopd** [comment]
Please merge https://github.com/oskardolch/SteamCAD/pull/7, that should fix it.

**Comment by probonopd** [comment]
Yay, it worked :+1: 

https://appimage.github.io/SteamCAD/

**Comment by oskardolch** [comment]
I checked the content of the image, the xml file is there, but I still see the old screenshot on https://appimage.github.io/SteamCAD/, what is wrong?

**Comment by oskardolch** [comment]
Ah, it is there now :-)
